import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
// import { Toaster } from "react-hot-toast";
import Footer from "./shared/footer";
import Navbar from "./shared/navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {/* <Toaster position="top-right" reverseOrder={false} /> */}
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
